In [1]:
import numpy as np
# 동일 데이터 타입으로 변환하여 사용
a = [1,2,3,'5']
ar = np.array(a).astype(int)
print(ar, type(ar))

[1 2 3 5] <class 'numpy.ndarray'>


In [6]:
# 차원(형태) 변환이 자유로움
a = range(12)
ar = np.array(a)
print(ar, '형태:', ar.shape)
ar34 = ar.reshape(3,4)
print(ar34, '차원:', ar34.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11] 형태: (12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 차원: (3, 4)


In [7]:
# 슬라이싱
ar34[1]

array([4, 5, 6, 7])